services:
  dcat:
    build: ./
    restart: "no"
    labels:
      - "logging=true"
    environment:
      - NODE_ENV=development
      - NO_BABEL_NODE=true
      - BASE_URL=https://ds.decide.lblod.info/
      - DSP_SERVICE_ID=urn:example:6e2e3fcb-8a66-4d81-a4cd-ba2eea954396
      - DSP_PARTICIPANT_ID=urn:example:DecideDataProvider
    ports:
      - "8083:80"
      - "9229:9229"
    volumes:
      - ./:/app
    networks:
      - debug
networks:
  debug:
    external: true
